const DATA_VERSION = {
  label: 'Set 18 pre-PBE theorycraft',
  updatedAt: '2026-07-13',
  confidence: 'Theorycraft — numbers and mechanics may change',
};

const UNITS = {
  Ahri: { cost: 4, traits: ['Blossom', 'Spellweaver'], role: 'AP carry', ability: 'Four-cost Blossom caster that receives Karma or Veigar items during the transition.' },
  Akali: { cost: 1, traits: ['Inferno', 'Adaptor', 'Ravager'], role: 'Melee carry', ability: 'Low-mana melee burst that converts offensive components into immediate Stage 2 pressure.' },
  Alistar: { cost: 2, traits: ['Elderwood', 'Brawler'], role: 'Main tank', ability: 'Durable Elderwood frontline that buys time for Xayah or later Rapidfire carries.' },
  Alune: { cost: 5, traits: ['Attuned', 'Lunar', 'Spellweaver'], role: 'Legendary AP carry', ability: 'High-value legendary caster and the premium end point for mana and AP components.' },
  Amumu: { cost: 4, traits: ['Inferno', 'Juggernaut'], role: 'Main tank', ability: 'Late Inferno frontline that lets a reroll core survive longer fights.' },
  Aphelios: { cost: 4, traits: ['Lunar', 'Rapidfire'], role: 'AD carry', ability: 'Four-cost bow carry that accepts Xayah, Varus, or Kayle item packages.' },
  Ashe: { cost: 5, traits: ['Blossom', 'Hunter'], role: 'Legendary AD carry', ability: 'Blossom cap carry for attack-speed and physical-damage components.' },
  Azir: { cost: 3, traits: ['Eldritch', 'Executioner', 'Summoner'], role: 'AP transition', ability: 'Summon-focused midgame bridge that activates Summoner and carries spare AP.' },
  Camille: { cost: 1, traits: ['Coven', 'Ravager'], role: 'Melee utility', ability: 'Cheap Ravager connector and secondary melee item holder.' },
  Cinderling: { cost: 1, traits: ['Riftbeast', 'Hunter'], role: 'Backline carry', ability: 'Cheap ranged damage that opens the Riftbeast vertical.' },
  Fiddlesticks: { cost: 3, traits: ['Flora Fatalis', 'Defender', 'Spellweaver'], role: 'AP utility', ability: 'Frontline-adjacent caster that adds control and Spellweaver scaling.' },
  Gnar: { cost: 5, traits: ['Elderwood', 'Sprykin', 'Brawler'], role: 'Legendary bruiser', ability: 'Premium flex unit that connects Elderwood, Sprykin, and Brawler caps.' },
  Gromp: { cost: 2, traits: ['Riftbeast', 'Adaptor'], role: 'Flexible bridge', ability: 'Mid-cost Riftbeast connector that keeps both AP and AD pivots open.' },
  Hecarim: { cost: 3, traits: ['Elderwood', 'Vanguard'], role: 'Main tank', ability: 'Stage 3 Elderwood tank that stabilizes before Lillia or Taric.' },
  Karma: { cost: 1, traits: ['Blossom', 'Spellweaver'], role: 'AP carry', ability: 'Tethers the target, deals magic damage over time, then bursts and slows nearby enemies.' },
  Kayle: { cost: 2, traits: ['Solar', 'Rapidfire'], role: 'Reroll carry', ability: 'Attack-speed scaling two-cost carry for a level 6 slow roll.' },
  Kennen: { cost: 5, traits: ['Inferno', 'Executioner'], role: 'Legendary AP carry', ability: 'Late Inferno finisher that converts leftover AP into board-wide pressure.' },
  Kobuko: { cost: 1, traits: ['Sprykin', 'Brawler'], role: 'Main tank', ability: 'Low-cost Brawler that makes Sprykin openers stable enough to hold economy.' },
  "Kog'Maw": { cost: 3, traits: ['Caustic', 'Invoker', 'Adaptor'], role: 'AP/on-hit carry', ability: 'Flexible three-cost carry for mana, AP, or attack-speed leaning items.' },
  Krug: { cost: 3, traits: ['Riftbeast', 'Brawler'], role: 'Main tank', ability: 'Midgame health anchor for deeper Riftbeast boards.' },
  LeBlanc: { cost: 2, traits: ['Elderwood', 'Spellweaver'], role: 'AP holder', ability: 'Natural AP item holder that preserves Elderwood and Spellweaver flexibility.' },
  Leona: { cost: 1, traits: ['Solar', 'Defender'], role: 'Main tank', ability: 'Reliable one-cost tank and the cleanest entry into Solar.' },
  Lillia: { cost: 4, traits: ['Fae', 'Defender'], role: 'Main tank', ability: 'Four-cost defensive cap that upgrades early Rakan or Ornn frontline items.' },
  Lux: { cost: 5, traits: ['Avatar'], role: 'Legendary AP carry', ability: 'Flexible legendary that can complete the most valuable trait or AP package.' },
  Maokai: { cost: 5, traits: ['Old Growth', 'Juggernaut'], role: 'Legendary tank', ability: 'Massive generic frontline for Fast 9 and Peeba boards.' },
  "Master Yi": { cost: 3, traits: ['Blossom', 'Adaptor'], role: 'AD transition', ability: 'Flexible Blossom bridge that can temporarily hold physical or hybrid items.' },
  Nidalee: { cost: 4, traits: ['Primal', 'Adaptor'], role: 'Flexible carry', ability: 'Four-cost flex piece that improves a capped Sprykin board without forcing one damage profile.' },
  Murkwolf: { cost: 2, traits: ['Riftbeast', 'Ravager'], role: 'Melee carry', ability: 'Two-cost melee damage and the most direct Riftbeast reroll target.' },
  Ornn: { cost: 1, traits: ['Elderwood', 'Defender'], role: 'Main tank', ability: 'Early Elderwood Defender that keeps almost every item direction open.' },
  Pebbles: { cost: 1, traits: ['Riftbeast', 'Invoker'], role: 'AP utility', ability: 'Cheap mana-oriented Riftbeast piece for AP-leaning openers.' },
  Rakan: { cost: 1, traits: ['Fae', 'Juggernaut', 'Vanguard'], role: 'Main tank', ability: 'Three-trait one-cost tank and one of the safest generic Stage 2 units.' },
  Rammus: { cost: 3, traits: ['Sprykin', 'Defender'], role: 'Main tank', ability: 'Three-cost tank spike that anchors both Tristana and Kog’Maw reroll branches.' },
  Raptor: { cost: 3, traits: ['Riftbeast', 'Summoner', 'Rapidfire'], role: 'AD carry', ability: 'Ranged three-cost damage and the best late reroll target in Riftbeast.' },
  "Rek'Sai": { cost: 1, traits: ['Eldritch', 'Brawler'], role: 'Main tank', ability: 'Simple early frontline that supports Eldritch and generic strongest-board play.' },
  Scuttlecrab: { cost: 2, traits: ['Riftbeast', 'Juggernaut'], role: 'Main tank', ability: 'High-value two-cost tank for Riftbeast or generic Juggernaut boards.' },
  Sejuani: { cost: 2, traits: ['Solar', 'Juggernaut'], role: 'Main tank', ability: 'Primary frontline reroll target beside Kayle.' },
  Sett: { cost: 4, traits: ['Blossom', 'Brawler'], role: 'Main tank', ability: 'Four-cost Blossom frontline that accepts every health and resistance item.' },
  Shen: { cost: 2, traits: ['Inferno', 'Defender'], role: 'Main tank', ability: 'Stable Inferno frontline and the preferred defensive bridge for Varus/Akali reroll.' },
  Sivir: { cost: 4, traits: ['Primal', 'Hunter'], role: 'AD carry', ability: 'Four-cost physical carry and temporary holder for Ashe items.' },
  Soraka: { cost: 4, traits: ['Flora Fatalis', 'Executioner'], role: 'AP utility', ability: 'Four-cost magic pressure and execution utility for expensive boards.' },
  Taric: { cost: 5, traits: ['Emerald Aspect', 'Vanguard'], role: 'Legendary tank', ability: 'Premium defensive splash that protects a single high-value carry.' },
  Teemo: { cost: 2, traits: ['Sprykin', 'Invoker'], role: 'AP utility', ability: 'Early Sprykin caster and clean mana-item bridge into Kog’Maw.' },
  "The Elder Dragon": { cost: 5, traits: ['Riftbeast', 'Apex Predator'], role: 'Legendary carry', ability: 'Vertical Riftbeast payoff and premium late-game damage sink.' },
  Tristana: { cost: 3, traits: ['Fae', 'Sprykin', 'Hunter'], role: 'AD carry', ability: 'Main physical three-cost reroll carry in the Sprykin branch.' },
  Varus: { cost: 1, traits: ['Inferno', 'Rapidfire'], role: 'AD carry', ability: 'One-cost ranged carry that cleanly holds bows and swords.' },
  Veigar: { cost: 1, traits: ['Eldritch', 'Sprykin', 'Spellweaver'], role: 'AP carry', ability: 'One-cost AP holder with exceptional trait connectivity.' },
  Vi: { cost: 3, traits: ['Primal', 'Juggernaut'], role: 'Frontline utility', ability: 'Durable Primal Juggernaut used to complete balanced Blossom caps.' },
  Xayah: { cost: 1, traits: ['Elderwood', 'Fae', 'Rapidfire'], role: 'AD carry', ability: 'One-cost bow holder with three useful transition traits.' },
  Yorick: { cost: 1, traits: ['Blossom', 'Juggernaut', 'Summoner'], role: 'Main tank', ability: 'Heals and strikes the target; on death, spawns a Spirit Walker.' },
  Yunara: { cost: 2, traits: ['Blossom', 'Executioner'], role: 'AD carry', ability: 'Strong early Blossom damage holder before Sivir or Ashe.' },
  Zyra: { cost: 4, traits: ['Thornmaiden', 'Summoner'], role: 'AP carry', ability: 'Four-cost summon carry and the main AP half of the Blossom cap.' },
};
